In [1]:
import numpy as np

#### Numpy arrays

In [3]:
arr = [20, 30, 40]
np_arr = np.array(arr)
np_arr

array([20, 30, 40])

In [4]:
arr = [[20, 30, 40], [20, 30, 40], [20, 30, 40]]
np_arr = np.array(arr)
np_arr

array([[20, 30, 40],
       [20, 30, 40],
       [20, 30, 40]])

#### arange

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2, dtype = np.float32)

array([0., 2., 4., 6., 8.], dtype=float32)

#### zeros

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3,4), dtype = np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### linspace : Evenly spaced numbers 

In [10]:
np.linspace(0, 20, 5) # start and stop inclusive, as opposed to range and arange.

array([ 0.,  5., 10., 15., 20.])

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])