In [1]:
import numpy as np

In [2]:
np.random.randn(4)

array([-0.37021788, -0.55666653, -0.34359841,  0.58625518])

In [3]:
np.random.randn(4,4)

array([[-0.0754027 , -0.51356991, -1.14384728, -1.91622075],
       [-0.32626425,  0.01900899, -0.0113826 , -1.2089416 ],
       [ 0.78592554,  0.2821492 ,  0.70719552,  0.60176615],
       [-0.42789431, -1.16583215,  0.31586532, -0.17355166]])

In [4]:
np.random.randint(1, 10) # 10 exclusive

9

In [5]:
np.random.randint(1, 10, 5)

array([1, 8, 8, 3, 7])

In [6]:
np.random.randint(1, 10, (4, 3))

array([[5, 2, 5],
       [6, 8, 9],
       [3, 4, 4],
       [8, 7, 9]])