In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3, 4, 5]
lst2 = lst[1:4]
lst2

[2, 3, 4]

In [3]:
np_arr = np.array(lst)
np_arr

array([1, 2, 3, 4, 5])

In [4]:
np_arr2 = np_arr[1:4]
np_arr2

array([2, 3, 4])

In [5]:
np_arr2 = 300
type(np_arr2) # -> int

int

In [6]:
np_arr2 = np_arr.copy()
np_arr2

array([1, 2, 3, 4, 5])

In [7]:
np_arr[:] = 700

In [8]:
np_arr

array([700, 700, 700, 700, 700])

In [9]:
np_arr2

array([1, 2, 3, 4, 5])

In [11]:
np_arr = np.random.randint(1, 20, 10)
np_arr

array([13,  4,  1,  9, 18, 15, 11, 16,  4, 19])

In [12]:
np_arr2 = np_arr[3:7]

In [13]:
np_arr2

array([ 9, 18, 15, 11])

#### To prevent this behaviour, use np.copy() method to assign one array to another.

In [14]:
np_arr2[:] = 25
np_arr2

array([25, 25, 25, 25])

In [15]:
np_arr

array([13,  4,  1, 25, 25, 25, 25, 16,  4, 19])