In [1]:
import numpy as np
import random

In [2]:
newList = np.arange(1, 21).reshape(5,4)
newList

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [3]:
newList[1, 2]

7

In [4]:
newList[1][2]

7

In [5]:
newList[1:, 2:]

array([[ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20]])

In [16]:
newList[[2, 0, 3]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [13, 14, 15, 16]])

#### Filtering

In [17]:
newList = np.random.randint(1, 100, 20)
newList

array([ 7,  1, 83,  1, 15, 44,  3, 97, 13, 11,  6, 12, 62, 91, 38, 25, 21,
        6, 38, 31])

In [18]:
newList > 24

array([False, False,  True, False, False,  True, False,  True, False,
       False, False, False,  True,  True,  True,  True, False, False,
        True,  True])

In [19]:
newList[newList > 24]

array([83, 44, 97, 62, 91, 38, 25, 38, 31])

#### Array Operations

In [20]:
lst = [1, 2, 3, 4]
lst

[1, 2, 3, 4]

In [21]:
lst + [1, 2, 4, 7]

[1, 2, 3, 4, 1, 2, 4, 7]

In [22]:
newList2 = np.random.randint(1, 100, 20)
newList2

array([78, 22, 27, 42, 24, 97, 58, 15, 37, 65, 39, 63, 18, 80, 11, 34, 77,
        4, 56, 76])

In [23]:
newList + newList2

array([ 85,  23, 110,  43,  39, 141,  61, 112,  50,  76,  45,  75,  80,
       171,  49,  59,  98,  10,  94, 107])

In [24]:
newList - newList2

array([-71, -21,  56, -41,  -9, -53, -55,  82, -24, -54, -33, -51,  44,
        11,  27,  -9, -56,   2, -18, -45])

In [25]:
newList * newList2

array([ 546,   22, 2241,   42,  360, 4268,  174, 1455,  481,  715,  234,
        756, 1116, 7280,  418,  850, 1617,   24, 2128, 2356])

In [26]:
newList / newList2
# if one of newList2 element is 0, returns NaN and continues to other divisions.

array([0.08974359, 0.04545455, 3.07407407, 0.02380952, 0.625     ,
       0.45360825, 0.05172414, 6.46666667, 0.35135135, 0.16923077,
       0.15384615, 0.19047619, 3.44444444, 1.1375    , 3.45454545,
       0.73529412, 0.27272727, 1.5       , 0.67857143, 0.40789474])

In [27]:
np.sqrt(newList)

array([2.64575131, 1.        , 9.11043358, 1.        , 3.87298335,
       6.63324958, 1.73205081, 9.8488578 , 3.60555128, 3.31662479,
       2.44948974, 3.46410162, 7.87400787, 9.53939201, 6.164414  ,
       5.        , 4.58257569, 2.44948974, 6.164414  , 5.56776436])

In [28]:
np.square(newList)

array([  49,    1, 6889,    1,  225, 1936,    9, 9409,  169,  121,   36,
        144, 3844, 8281, 1444,  625,  441,   36, 1444,  961], dtype=int32)